# Calamares top-level configuration - Goudunix fork.
#
# Based on upstream calamares-nixos-extensions settings.conf; the only
# change is replacing `packagechooser` with our own `goudupackages` QML
# view module in the sequence.
---
modules-search: [ local, @out@/lib/calamares/modules ]

instances:
- id:       unfree
  module:   notesqml
  config:   unfree.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - users
  - goudupackages
  - notesqml@unfree
  - partition
  - summary
- exec:
  - partition
  - mount
  - nixos
  - users
  - umount
- show:
  - finished

branding: goudunix

prompt-install: false

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: false

quit-at-end: false
